### PR TITLE
Update to font awesome icons 5.15

### LINKED ISSUE #114: Update icons to most recent version
Could you update to support 5.14 versions?

### PR DESCRIPTION
**Pull request by michaelspiss**
Fixes #114 by providing most up-to-date iconset. Supersedes #115.

### CODE REVIEW

**Review by brianegan — APPROVED** [review]
Looks great!  Thanks again for all your help supporting this library :)

**Comment by michaelspiss** [comment]
Ah I didn't know that - one second

**Comment by michaelspiss** [comment]
Pub says "insufficient permissions to upload new versions" - could you please re-check I've been added?

**Comment by brianegan** [comment]
@jeroen-meijer Heya Jay! I'd like to add Michael to the uploaders on this package, but I'm unable to since moving the package over to the FlutterCommunity. I'm getting the error:

```
Package "font_awesome_flutter" is owned by publisher "fluttercommunity.dev". Updating the uploaders is not permitted.
```

Could you please let me know how we can add him? Thanks!

**Comment by jeroen-meijer** [comment]
Hey @brianegan, long time no see!

I'll see it done right away. 👍🏻

**Comment by jeroen-meijer** [comment]
@brianegan @michaelspiss Sorry, completely forgot about this... 😅

@michaelspiss What's the email that you want to upload from?

**Comment by michaelspiss** [comment]
No problem, it's michaelspiss.dev@mailbox.org

**Comment by jeroen-meijer** [comment]
Done!
@michaelspiss You should be added now.

**Comment by michaelspiss** [comment]
It still displays the "insufficient permissions" error - I tried logging out and in again, but that didn't help

**Comment by brianegan** [comment]
For sure, thank you both!

**Pull request merged**
