### PR TITLE
Add ability to pull font metadata from FontAwesome API instead of ico…

### PR DESCRIPTION
**Pull request by ryanawhelan**
Add ability to pull font metadata from FontAwesome API instead of icons.json since icons.json doesn't appear to be updated regularly/accurately.

Added ability to get Pro or Free icons from API
Added args for pro/free, use API instead of icons.json, debug API,
update example to support FontAwesome 6.0.0
update example to fully use Android v2 embedding
update gradle version
update kotlin plugin
update compileSdkVersion

### CODE REVIEW

**Comment by devj3ns** [comment]
Hey @ryanawhelan, unfortunately it does not work for me.

I imported it with

```yaml
font_awesome_flutter:
    git: https://github.com/ryanawhelan/font_awesome_flutter
```
and tested with
```dart
FaIcon(FontAwesomeIcons.check),
```
which throws

```
Error: unable to locate asset entry in pubspec.yaml: "lib/fonts/fa-light-300.ttf".
Failed to compile application.
```

**Comment by ryanawhelan** [comment]
I see, I checked in the modified pubspec.yaml with the pro font files uncommented.  This is fixed. Can you update and try again?
configurator.sh (or bat) -defaults to none-pro version, but you would add --pro if you have the pro icons.

**Comment by devj3ns** [comment]
> @devj3ns I see, I checked in the modified pubspec.yaml with the pro font files uncommented. This is fixed. Can you update and try again? configurator.sh (or bat) -defaults to none-pro version, but you would add --pro if you have the pro icons.

Now I don't get the error anymore, nice! (I don't have pro).

Unfortunately, I don't have access to the new icons (e.g., `chart-column` or `mask-face`).
When I open my local `font_awesome_flutter.dart` file in `/lib` it says: `/// Icons based on font awesome 5.15.4`

I think something is not working correctly.

**Comment by michaelspiss** [comment]
@devj3ns you need to run `flutter pub get` once in the main repository for pub the get all the dependencies.

**Comment by michaelspiss** [comment]
Hey, thanks @ryanawhelan so much for putting your effort into this.
I still hope they'll bring back the icon metadata, as I see many issues with the GraphQL API approach.

You already discovered my main usability concern: We either attach this package's version to a specific version of font awesome, or the user has to enter their version number and pro/free every time they run the generator. It should also not be a necessity to have internet access to build otherwise local files (especially important for larger companies).

If you have font awesome pro and it is connected to your Github account, you can see my full reasoning here: [fa-pro repository](https://github.com/FortAwesome/Font-Awesome-Pro/issues/1577).

I won't merge this pull request anytime soon but will leave it open as long as we don't have a clear answer by the font awesome developers. People who need v6 _right now_ can use this patch. Should FA decide to drop the metadata folder completely, we'll work to get your code into the main package.

I hope this sounds reasonable and is in your interest as well.

**Comment by ryanawhelan** [comment]
@michaelspiss 

Understood.    We use 6.0 and Pro so I needed this personally and was just hoping to help if other people could benefit.    I can totally understand wanting to wait, but from what I have heard from other developers, the metadata (icons.json) from later 5.0 versions was not being well maintained anyway, so I think the FontAwesome people lost a lot of interest in maintaining two copies of their font metadata.  

Another option would be to pull the API code out of main.dart and have it generate an icons.json file from the API.  I assume this is probably what the FontAwesome people would do anyway (extract the json from their existing database, but probably not in Dart).

**Comment by michaelspiss** [comment]
Closing as icons.json is available again starting version 6.1.0.
Nonetheless, thanks @ryanawhelan for your help bridging these months!

**Pull request closed without merging**
