### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by brianegan**

### CODE REVIEW

**Comment by michaelspiss** [comment]
Awesome, thank you! Just a quick question, do you have access to the github tools? When I go to settings, most are hidden

**Comment by brianegan** [comment]
I do! I found this under: Settings > Features > Issue Templates > Set up Templates.

**Comment by brianegan** [comment]
Gotcha. 

I just upgraded you to an "Admin" role. Does that help at all?

**Comment by michaelspiss** [comment]
Perfect, now everything's there - thanks!

**Comment by brianegan** [comment]
Sweet -- just don't kick me out of the repo!!! :P

**Comment by brianegan** [comment]
Hm, I actually didn't change anything there. 

I'm a general Flutter Community admin, so I guess I have admin priveledges on all repos.

**Comment by michaelspiss** [comment]
I only added the fa version information back to the readme and removed the styles list as it is no longer up-to-date for free icons.
Thanks again for your help!

**Comment by brianegan** [comment]
Good call, thanks for reviewing that!

**Pull request merged**
