### PR TITLE
Added Flutter/Dart lints to project.

### PR DESCRIPTION
**Pull request by gslender**
Fixed all warnings, except example which won't patch correctly if changed. All changes made were only because they are marked as bad style or potentially allows risky code to exist which should be changed to avoid future errors.

### CODE REVIEW

**Comment by michaelspiss** [comment]
Thanks! I fixed the remaining linter infos in the example and adjusted the duotone patch accordingly. Please have a look if everything is as you'd expect. I'd then merge.

**Comment by gslender** [comment]
Looks good to me 👍

**Comment by gslender** [comment]
Sorry... clicked the wrong button

**Comment by michaelspiss** [comment]
Thanks again!

**Pull request merged**
