### PR TITLE
Values map and v5.12.1

### PR DESCRIPTION
**Pull request by JuanM04**
* Upgrade to Font Awesome Icons 5.12.1
* Add `values` map that lists all icons.
* Add `final` keyword where possible.
* Set minimal Dart SDK version to v2.2.2

### CODE REVIEW

**Comment by brianegan** [comment]
Hey -- thanks much! Appreciate the update, but I unfortunately can't accept any PRs with a `values` array / map / etc. The idea comes up a lot, and must be valuable, but every person who asks for it would like it to work a different way (different naming conventions, some folks want a list, others want a map, etc). Therefore, I think it's best to leave it out of this core library and let folks generate it in the way you've done if they need it for their projects.

**Comment by JuanM04** [comment]
I understand you. Personally, a map is a list (because you can always do `Map.values`) with the ability of saving an icon as text

**Comment by brianegan** [comment]
Yah, it's always a bit tough. 

You're totally right about map as a list, but a lot of folks have different naming conventions for the keys in the map. Some use an older Font Awesome 4.x approach, others use the 5.x approach, others use the approach we take in this lib -- so overall it's kind of impossible to make it work for everyone.

**Comment by JuanM04** [comment]
What a bummer.

What if you use democracy? You can create a [StrawPoll](https://www.strawpoll.me/) (or something similar) and let the community vote

**Comment by brianegan** [comment]
I can understand the disappointment, but it's not really a matter of democracy -- it's rather there isn't a one-sized-fits-all solution naming convention or solution that will work for everyone. If you're interested, please read through #10 to understand a bit more why!

**Pull request closed without merging**
